# This notebook is used to implement tensor arithmetic.

In [1]:
import numpy as np

## Tensor creation

In [2]:
T = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26,27]]])

In [3]:
print(T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


## Tensor addition

In [4]:
print(T + 1)

[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]


## Tensor product

In [11]:
A = np.array([1, 2])
B = np.array([3, 4])
C = np.tensordot(A, B, axes=0)
print(C)

[[3 4]
 [6 8]]


In [13]:
C2 = np.tensordot(A, B, axes=1)
print(C2)

11


In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 1], [1, 1], [1, 1]])
C = np.tensordot(A, B, axes=0)
print(C)
print(C.shape)

[[[[1 1]
   [1 1]
   [1 1]]

  [[2 2]
   [2 2]
   [2 2]]]


 [[[3 3]
   [3 3]
   [3 3]]

  [[4 4]
   [4 4]
   [4 4]]]]
(2, 2, 3, 2)


In [17]:
C2 = np.tensordot(A, B[:-1, :], axes=1)
print(B[:-1, :])
print(C2)

[[1 1]
 [1 1]]
[[3 3]
 [7 7]]
